// Generated by Vercel during build. This placeholder is only for local source packages.
window.PRIOWEEK_CONFIG = {
  containerIdentifier: "iCloud.com.prioweek.app",
  environment: "production",
  apiToken: ""
};
